### PR TITLE
fix: Cleaning travis code

### PR DESCRIPTION
**Pull request by ravali-rimmalapudi**
# Fixes #

A short description of what this PR does.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Review by onuzbee — APPROVED** [review]
👍🏻

**Comment by shrutiburman** [comment]
I see a test case failed [here](https://github.com/twilio/twilio-cli/runs/5047333867?check_suite_focus=true#step:6:424), is it related to the change?

**Comment by ravali-rimmalapudi** [comment]
> I see a test case failed [here](https://github.com/twilio/twilio-cli/runs/5047333867?check_suite_focus=true#step:6:424), is it related to the change?

The failures are because of output properties https://github.com/twilio/twilio-cli/runs/5062485427?check_suite_focus=true#step:6:426. I think we have a dependency change in cli-core. @kridai Can you please confirm this?

**Review by shrutiburman — APPROVED** [review]

**Comment by kridai** [comment]
> > I see a test case failed [here](https://github.com/twilio/twilio-cli/runs/5047333867?check_suite_focus=true#step:6:424), is it related to the change?
> 
> The failures are because of output properties https://github.com/twilio/twilio-cli/runs/5062485427?check_suite_focus=true#step:6:426. I think we have a dependency change in cli-core. @kridai Can you please confirm this?

Yeah, I have fixed it as part of https://github.com/twilio/twilio-cli/pull/382. @ravali-rimmalapudi can you merge the latest from twilio-cli main

**Pull request merged**
