### PR TITLE
feat: Release feature branch

### PR DESCRIPTION
**Pull request by ravali-rimmalapudi**
# Fixes #

[DII-250](https://issues.corp.twilio.com/browse/DII-250): Merging release feature branch into main

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by onuzbee** [comment]
`major` - Since we'd want to bump the major version for this breaking change, let's mark the PR/commit title with `BREAKING CHANGE`?

**Comment by ravali-rimmalapudi** [comment]
> `major` - Since we'd want to bump the major version for this breaking change, let's mark the PR/commit title with `BREAKING CHANGE`?

Yes, we should add commit body as BREAKING CHANGE, something like [this](https://github.com/LakshmiRavali/twilio-cli-core/commit/cdb7a694590668ec2669c647e29ac1fab40a8351)
@shrutiburman when you do the release from forked repo, check if it's bumping to major version.

**Comment by onuzbee** [comment]
Basic sanity done:

- Pulled locally and built (marking release-feature-branch of twilio-cli-core). `plugin-update` caused additional security vulnerabilities- Bumping the version fixed it. 
- `npm test` - UTs passing

Need to rigorously test for profiles functionality.

**Comment by ravali-rimmalapudi** [comment]
> [Note]- Need to bump this to 2.1.3 - Causing security vulnerabilities with local testing

After updating to 2.1.3, Still seeing 5 vulnerabilities 
image
@onuzbee Is this expected?

**Comment by onuzbee** [comment]
> > [Note]- Need to bump this to 2.1.3 - Causing security vulnerabilities with local testing
> 
> After updating to 2.1.3, Still seeing 5 vulnerabilities image @onuzbee Is this expected?

Yes, This is pending updates from oclif. `plugin-update` was causing a few extra vulnerabilities.

**Review by onuzbee — APPROVED** [review]
LGTM! 🚀 

Side note- 
1. [MAJOR] Please add `BREAKING CHANGE` while merging the PR.
2. Testing roughly by pulling in `release-feature-branch`. But, need to rigorously test against use-cases after pushing to `main`.

**Review by kridai — APPROVED** [review]

**Review by shamantraghav — APPROVED** [review]

**Pull request merged**
