### PR TITLE
fix: Update release feature branch

### PR DESCRIPTION
**Pull request by ravali-rimmalapudi**
# Fixes #

Updating the release feature branch
Test Gist: [Link](https://gist.github.com/ravali-rimmalapudi/b330827ee1a984e602a0abb587d3a966)

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-cli/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by onuzbee** [comment]
Were these commits cherry-picked manually? Any idea on how to verify for any commit we might have missed post this merge?

**Comment by kridai** [comment]
> Were these commits cherry-picked manually? Any idea on how to verify for any commit we might have missed post this merge?

Ravali had these commits in her forked repo for release-feature-branch. We did try and check the commits of the closed PRs by each member for release feature branch to be present here. We can all do the same to verify.

**Comment by ravali-rimmalapudi** [comment]
> Were these commits cherry-picked manually? Any idea on how to verify for any commit we might have missed post this merge?

No, These commits are from [my forked repo](https://github.com/ravali-rimmalapudi/twilio-cli/tree/release-feature-branch). I didn't pulled the latest changes from `twilio-cli` release-feature-branch. You can test it locally by checking out to my forked repo `release-feature-branch` and point cli-core to `twilio-cli-core` `release-feature-branch`.

**Comment by shrutiburman** [comment]
Okay. Do you have any possible root causes for this? It'd help in narrowing down the manual effort of comparing. If not, I feel we should also verify commits before June, just to be sure.

**Comment by ravali-rimmalapudi** [comment]
> Okay. Do you have any possible root causes for this? It'd help in narrowing down the manual effort of comparing. If not, I feel we should also verify commits before June, just to be sure.

I wasn't sure exact root cause suspecting because of merging of main to release-feature-branch might not be proper. We created release-feature-branch after we joined only, so we tested the closed PR's by all our teammates and [verified it](https://github.com/twilio/twilio-cli/pulls?q=is%3Apr+is%3Aclosed+author%3Aravali-rimmalapudi). You can also verify it from your side.

**Comment by onuzbee** [comment]
I see UTs failing. Is it a similar case for `twilio-cli-core` that commits are missing there?  
I see `twilio-cli-core` being pointed to the main release, which might hint some missing commits that pinned to the `-rc` tag for `cli-core` (Which is causing these failures). 


Example: 
```
commands
       profiles
         remove
           run profiles:remove with the last configured profile in keytar and delete all keys:
     TypeError: Cannot read properties of undefined (reading 'removeCallback')
      at Object.finally (node_modules/@twilio/cli-test/src/index.js:65:27)
      at Context.run (node_modules/fancy-test/lib/base.js:79:36)
```

**Comment by ravali-rimmalapudi** [comment]
> I see UTs failing. Is it a similar case for `twilio-cli-core` that commits are missing there? I see `twilio-cli-core` being pointed to the main release, which might hint some missing commits that pinned to the `-rc` tag for `cli-core` (Which is causing these failures).
> 
> Example:
> 
> ```
> commands
>        profiles
>          remove
>            run profiles:remove with the last configured profile in keytar and delete all keys:
>      TypeError: Cannot read properties of undefined (reading 'removeCallback')
>       at Object.finally (node_modules/@twilio/cli-test/src/index.js:65:27)
>       at Context.run (node_modules/fancy-test/lib/base.js:79:36)
> ```

As far as my check in `twilio-cli-core`,  commits are there. Can you also verify once. And regarding the test failure it is because of `cli-core` is pointing to `main` tag, I ran the tests locally by pointing to `release-feature-branch` and posted the gist link in the PR. 
Currently in the last release candidate release `cli-core` is not released to npm so we didn't updated in here. After today's `cli-core` release, I will update it with correct version and release cli.

**Review by kridai — APPROVED** [review]

**Comment by ravali-rimmalapudi** [comment]
> > I see UTs failing. Is it a similar case for `twilio-cli-core` that commits are missing there? I see `twilio-cli-core` being pointed to the main release, which might hint some missing commits that pinned to the `-rc` tag for `cli-core` (Which is causing these failures).
> > Example:
> > ```
> > commands
> >        profiles
> >          remove
> >            run profiles:remove with the last configured profile in keytar and delete all keys:
> >      TypeError: Cannot read properties of undefined (reading 'removeCallback')
> >       at Object.finally (node_modules/@twilio/cli-test/src/index.js:65:27)
> >       at Context.run (node_modules/fancy-test/lib/base.js:79:36)
> > ```
> 
> As far as my check in `twilio-cli-core`, commits are there. Can you also verify once. And regarding the test failure it is because of `cli-core` is pointing to `main` tag, I ran the tests locally by pointing to `release-feature-branch` and posted the gist link in the PR. Currently in the last release candidate release `cli-core` is not released to npm so we updated it main release while [resolving the conflicts](https://github.com/twilio/twilio-cli/pull/330/commits/cbee44cafca69f90d8f03e4f72f6bae58466869d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R47). After today's `cli-core` release, I will update it with correct version and release cli.



> > I see UTs failing. Is it a similar case for `twilio-cli-core` that commits are missing there? I see `twilio-cli-core` being pointed to the main release, which might hint some missing commits that pinned to the `-rc` tag for `cli-core` (Which is causing these failures).
> > Example:
> > ```
> > commands
> >        profiles
> >          remove
> >            run profiles:remove with the last configured profile in keytar and delete all keys:
> >      TypeError: Cannot read properties of undefined (reading 'removeCallback')
> >       at Object.finally (node_modules/@twilio/cli-test/src/index.js:65:27)
> >       at Context.run (node_modules/fancy-test/lib/base.js:79:36)
> > ```
> 
> As far as my check in `twilio-cli-core`, commits are there. Can you also verify once. And regarding the test failure it is because of `cli-core` is pointing to `main` tag, I ran the tests locally by pointing to `release-feature-branch` and posted the gist link in the PR. Currently in the last release candidate release `cli-core` is not released to npm so we updated it main release while [resolving the conflicts](https://github.com/twilio/twilio-cli/pull/330/commits/cbee44cafca69f90d8f03e4f72f6bae58466869d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R47). After today's `cli-core` release, I will update it with correct version and release cli.

Please review the [merge commit](https://github.com/twilio/twilio-cli/pull/330/commits/cbee44cafca69f90d8f03e4f72f6bae58466869d). If you think any changes we missed/overwritten while resolving the conflicts, Please let us know.

**Review by onuzbee — APPROVED** [review]
👍🏻

**Review by shrutiburman — APPROVED** [review]

**Pull request merged**
